cmd /c certutil -addstore -f "Root" ..\certs\oracle-cert.cer"
cmd /c certutil -addstore -f "Root" ..\certs\gdig2.crt"
cmd /c certutil -addstore -f "Root" ..\certs\comodorsadomainvalidationsecureserverca.crt"
cmd /c certutil -addstore -f "Root" ..\certs\comodorsacertificationauthority.crt"
cmd /c certutil -addstore -f "Root" ..\certs\addtrust_external_ca.cer"
cmd /c certutil -addstore -f "Root" ..\certs\baltimore_ca.cer"
cmd /c certutil -addstore -f "Root" ..\certs\digicert.cer"
cmd /c certutil -addstore -f "Root" ..\certs\equifax.cer"
cmd /c certutil -addstore -f "Root" ..\certs\globalsign.cer"
cmd /c certutil -addstore -f "Root" ..\certs\gte_cybertrust.cer"
cmd /c certutil -addstore -f "Root" ..\certs\microsoft_root_2011.cer"
cmd /c certutil -addstore -f "Root" ..\certs\thawte_primary_root.cer"
cmd /c certutil -addstore -f "Root" ..\certs\utn-userfirst.cer"
pause